In [1]:
import numpy as np

In [3]:
sb = np.matrix('8 0; 0 0')
sb

matrix([[8, 0],
        [0, 0]])

In [13]:
d1 = np.matrix([1,1]).T
d2 = np.matrix([2,1]).T

In [14]:
mu1 = np.matrix([4,0]).T
mu2 = np.matrix([0,0]).T

In [15]:
## class 1
sw = np.dot((d1 - mu1), (d1 - mu1).T) + np.dot((d2 - mu1), (d2 - mu1).T)
## class 2
sw += np.dot((d1 - mu2), (d1 - mu2).T) + np.dot((d2 - mu2), (d2 - mu2).T)
sw

matrix([[18, -2],
        [-2,  4]])

In [16]:
A = np.linalg.inv(sw).dot(sb)
A

matrix([[0.47058824, 0.        ],
        [0.23529412, 0.        ]])

In [18]:
eigenvalue, eigenvactoes = np.linalg.eig(A)

In [20]:
eigenvactoes

matrix([[0.        , 0.89442719],
        [1.        , 0.4472136 ]])

In [22]:
eigenvalue

array([0.        , 0.47058824])

In [26]:
U = eigenvactoes[:,1]

In [27]:
U

matrix([[0.89442719],
        [0.4472136 ]])

In [33]:
## projection
U.T.dot(d1)

matrix([[1.34164079]])

In [30]:
d1.shape

(2, 1)

In [32]:
U.T.shape

(1, 2)